package basics.multithreading;

// Synchronized without the static 

// class Brackets {
 
// 	synchronized public void generate() {
// 		for (int i = 1; i <= 10; i++) {
// 			if (i <= 5) {
// 				System.out.print("[");
// 			} else {
// 				System.out.print("]");
// 			}
// 		}
// 		System.out.println();
// 	}
 
// }
 
// public class StaticSynchronised {
 
// 	public static void main(String[] args) {
// 		Brackets bracket1 = new Brackets();
// 		Brackets bracket2 = new Brackets();
// 		new Thread(new Runnable() {
 
// 			@Override
// 			public void run() {
// 				for (int i = 1; i <= 5; i++) {
// 					bracket1.generate();
// 				}
 
// 			}
// 		}).start();
 
// 		new Thread(new Runnable() {
 
// 			@Override
// 			public void run() {
// 				for (int i = 1; i <= 5; i++) {
// 					bracket2.generate();
// 				}
 
// 			}
// 		}).start();
 
// 	}
 
// }

// it may give an inconsistence output
// output :-

// [[[[[]]]]][[[[[]]]]]
// [[[[[]]]
// [[[[[]]]]]
// [[[[[]]]]]
// [[[[[]]]]]
// [[[[[]]]]]
// ]]
// [[[[[]]]]]
// [[[[[]]]]]
// [[[[[]]]]]


// Synchronized with the static 

class Brackets{

	synchronized static public void generate(String threadCode){
		for(int i=1; i<=10; i++){
			if(i<=5){
				System.out.print("[");
			}else{
				System.out.print("]");
			}
		}
		System.out.println("Generated by thread: "+threadCode);
	}
	
}

public class StaticSynchronised {
    public static void main(String[] args) {
		
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				for(int i=1; i<=5; i++){
					Brackets.generate("Thread 1");
				}
 
			}
		}).start();
		
       new Thread(new Runnable() {
			
			@Override
			public void run() {
				for(int i=1; i<=5; i++){
					Brackets.generate("Thread 2");
				}
 
			}
		}).start();
		
 
	}
}

// output :-

// [[[[[]]]]]Generated by thread: Thread 1
// [[[[[]]]]]Generated by thread: Thread 1
// [[[[[]]]]]Generated by thread: Thread 1
// [[[[[]]]]]Generated by thread: Thread 1
// [[[[[]]]]]Generated by thread: Thread 1
// [[[[[]]]]]Generated by thread: Thread 2
// [[[[[]]]]]Generated by thread: Thread 2
// [[[[[]]]]]Generated by thread: Thread 2
// [[[[[]]]]]Generated by thread: Thread 2
// [[[[[]]]]]Generated by thread: Thread 2